flags: {}
nix:
  enable: true
  shell-file: shell.nix
extra-package-dbs: []
packages:
- '.'
extra-deps:
- base58-bytestring-0.1.0
- blaze-builder-0.3.3.4
- io-streams-1.2.1.3
- multihash-0.1.2
- secp256k1-0.4.6
resolver: lts-3.22
