flags: {}
nix:
  enable: false
  shell-file: shell.nix
extra-package-dbs: []
packages:
- .
- location:
    git: git@github.com:MatrixAI/haskell-multihash.git
    commit: 0c95cb0efb72c6d3dc1cd1e092be75f5a0f78210
  extra-dep: true
- location:
    git: git@github.com:MatrixAI/haskell-libp2p-crypto.git
    commit: f23d9903215af5b7f9468084da776081fd4a06b5
  extra-dep: true
extra-deps:
- base58-bytestring-0.1.0
- hprotoc-2.4.2
- secp256k1-0.4.8
- haskell-src-exts-1.17.1
resolver: lts-9.0
