flags: {}
nix:
  enable: false
  shell-file: shell.nix
extra-package-dbs: []
packages:
- .
- location:
    git: git@github.com:MatrixAI/haskell-multihash.git
    commit: b604fab178d24e3fcb5b638e5bcba6b2e9265fb6 
  extra-dep: true
- location:
    git: git@github.com:MatrixAI/haskell-libp2p-crypto.git
    commit: ccd135c96552ef2b8896e692a620f11c75fcb78a
  extra-dep: true
extra-deps:
- base58-bytestring-0.1.0
- hprotoc-2.4.2
- secp256k1-0.4.8
- haskell-src-exts-1.17.1
resolver: lts-9.0
